import fs from 'fs';
import path from 'path';
import type { Route } from '../models/route.js';
import type { Secret } from '../models/secret.js';

export interface RouteDiff {
  added: Route[];
  removed: Route[];
}

export interface SecretDiff {
  newFound: Secret[];    // 在新版出現，舊版沒有
  resolved: Secret[];   // 在舊版有，新版消失（可能已修復）
}

export interface ScanDiff {
  oldDir: string;
  newDir: string;
  routes: RouteDiff;
  secrets: SecretDiff;
  routeKey: (r: Route) => string;
}

function routeKey(r: Route): string {
  return `${r.httpMethod}:${r.path}`;
}

function secretKey(s: Secret): string {
  return `${s.ruleId}:${path.basename(s.filePath)}:${s.lineNumber}`;
}

function loadJson<T>(dir: string, filename: string): T[] {
  const filePath = path.join(dir, filename);
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8')) as T[];
  } catch {
    return [];
  }
}

export function diffScans(oldDir: string, newDir: string): ScanDiff {
  const oldRoutes = loadJson<Route>(oldDir, 'routes.json');
  const newRoutes = loadJson<Route>(newDir, 'routes.json');
  const oldSecrets = loadJson<Secret>(oldDir, 'secrets-report.json');
  const newSecrets = loadJson<Secret>(newDir, 'secrets-report.json');

  const oldRouteKeys = new Set(oldRoutes.map(routeKey));
  const newRouteKeys = new Set(newRoutes.map(routeKey));
  const oldSecretKeys = new Set(oldSecrets.map(secretKey));
  const newSecretKeys = new Set(newSecrets.map(secretKey));

  return {
    oldDir,
    newDir,
    routeKey,
    routes: {
      added:   newRoutes.filter(r => !oldRouteKeys.has(routeKey(r))),
      removed: oldRoutes.filter(r => !newRouteKeys.has(routeKey(r))),
    },
    secrets: {
      newFound: newSecrets.filter(s => !oldSecretKeys.has(secretKey(s))),
      resolved: oldSecrets.filter(s => !newSecretKeys.has(secretKey(s))),
    },
  };
}

export function formatDiffMarkdown(diff: ScanDiff): string {
  const lines: string[] = [];
  const hasChanges = diff.routes.added.length || diff.routes.removed.length ||
                     diff.secrets.newFound.length || diff.secrets.resolved.length;

  lines.push('# LCP Diff Report');
  lines.push('');
  lines.push(`**Old:** \`${diff.oldDir}\``);
  lines.push(`**New:** \`${diff.newDir}\``);
  lines.push('');

  if (!hasChanges) {
    lines.push('## ✅ No Changes Detected');
    lines.push('Routes and secrets are identical between the two scans.');
    return lines.join('\n');
  }

  // Route diff
  lines.push('## Routes');
  lines.push('');

  if (diff.routes.added.length > 0) {
    lines.push(`### ✅ Added (${diff.routes.added.length})`);
    lines.push('| Method | Path | Handler |');
    lines.push('|--------|------|---------|');
    for (const r of diff.routes.added) {
      const handler = r.className ? `${r.className}#${r.methodName ?? ''}` : '-';
      lines.push(`| \`${r.httpMethod}\` | \`${r.path}\` | ${handler} |`);
    }
    lines.push('');
  }

  if (diff.routes.removed.length > 0) {
    lines.push(`### ❌ Removed (${diff.routes.removed.length})`);
    lines.push('| Method | Path | Handler |');
    lines.push('|--------|------|---------|');
    for (const r of diff.routes.removed) {
      const handler = r.className ? `${r.className}#${r.methodName ?? ''}` : '-';
      lines.push(`| \`${r.httpMethod}\` | \`${r.path}\` | ${handler} |`);
    }
    lines.push('');
  }

  if (!diff.routes.added.length && !diff.routes.removed.length) {
    lines.push('_No route changes._');
    lines.push('');
  }

  // Secret diff
  lines.push('## Secrets');
  lines.push('');

  if (diff.secrets.newFound.length > 0) {
    lines.push(`### 🔴 Newly Detected (${diff.secrets.newFound.length})`);
    lines.push('| Severity | Type | File | Line | Masked |');
    lines.push('|----------|------|------|------|--------|');
    for (const s of diff.secrets.newFound) {
      lines.push(`| ${s.severity} | ${s.secretType} | \`${path.basename(s.filePath)}\` | ${s.lineNumber} | \`${s.maskedValue}\` |`);
    }
    lines.push('');
  }

  if (diff.secrets.resolved.length > 0) {
    lines.push(`### ✅ Resolved / Removed (${diff.secrets.resolved.length})`);
    lines.push('| Severity | Type | File | Line |');
    lines.push('|----------|------|------|------|');
    for (const s of diff.secrets.resolved) {
      lines.push(`| ${s.severity} | ${s.secretType} | \`${path.basename(s.filePath)}\` | ${s.lineNumber} |`);
    }
    lines.push('');
  }

  if (!diff.secrets.newFound.length && !diff.secrets.resolved.length) {
    lines.push('_No secret changes._');
    lines.push('');
  }

  lines.push('---');
  lines.push('_Generated by Legacy Context Packager_');

  return lines.join('\n');
}
