import fs from 'fs';
import path from 'path';
import type { ProjectScanResult } from '../models/context-pack.js';
import type { Route } from '../models/route.js';
import { buildReportHtml } from './report-builder.js';
import type { PkgDep } from '../models/pkg-dep.js';

export interface OutputOptions {
  outputDir: string;
  report?: boolean; // 是否同時產出 report.html（預設 true）
}

export function buildOutput(result: ProjectScanResult, opts: OutputOptions): void {
  fs.mkdirSync(opts.outputDir, { recursive: true });

  const md = buildMarkdown(result);
  fs.writeFileSync(path.join(opts.outputDir, 'context-pack.md'), md, 'utf8');

  if (opts.report !== false) {
    const html = buildReportHtml(result);
    fs.writeFileSync(path.join(opts.outputDir, 'report.html'), html, 'utf8');
  }
}

function buildMarkdown(r: ProjectScanResult): string {
  const lines: string[] = [];
  const { projectInfo: p } = r;

  lines.push(`# Context Pack — ${path.basename(p.rootPath)}`);
  lines.push(`\n> Language: \`${p.language}\` | Framework: \`${p.framework}\` | Scanned: ${p.scannedFiles}/${p.totalFiles} files | Duration: ${p.scanDurationMs}ms`);
  lines.push(`
## 給 LLM 的說明

你收到的是一份由靜態分析工具自動產生的遺留系統盤點摘要，資料來自原始碼的靜態掃描，未執行程式。請依下列順序完成系統盤點：

1. **技術棧摘要**：根據語言、框架與 config 檔案，描述此系統的技術選型與部署特徵
2. **功能模組拆解**：根據 Routes 的 Controller 分組，推斷各模組的職責與邊界
3. **前後端銜接**：對照 Web Entries 與 Routes，找出前端呼叫但後端可能缺少對應的路徑
4. **安全風險摘要**：若 Secrets 有資料，依嚴重程度列出需優先處理的項目；若無則標注「未偵測到硬編碼敏感值」
5. **盤點結論**：以條列式輸出「已釐清」與「需人工確認」的項目

**資料品質說明：**
- \`confidence: high\` 表示規則明確比對，可信度高
- \`confidence: medium / low\` 表示推斷結果，建議人工核實
- 動態路由、反射、自訂 middleware 產生的 API 不會出現在以下資料中`);

  // 統計摘要
  lines.push('\n## 系統摘要');
  lines.push(buildStatsSummary(r));

  // 套件依賴（有資料才輸出）
  if (r.pkgDeps.length > 0) {
    lines.push('\n## 主要依賴');
    lines.push(buildPkgDepsSection(r.pkgDeps));
  }

  lines.push('\n## API Map');
  lines.push(buildApiMapSection(r.routes, p.rootPath));

  lines.push('\n## Web Entries');
  if (r.webEntries.length === 0) {
    lines.push('_No web entries found._');
  } else {
    lines.push('| Type | Source | Target | Invoke |');
    lines.push('|------|--------|--------|--------|');
    for (const e of r.webEntries) {
      lines.push(`| ${e.entryType} | ${path.basename(e.sourceFile)}:${e.lineNumber} | \`${e.targetPath}\` | ${e.invokeType} |`);
    }
  }

  lines.push('\n## Secrets');
  if (r.secrets.length === 0) {
    lines.push('_No secrets detected._');
  } else {
    lines.push('| Severity | Type | File | Line | Masked Value |');
    lines.push('|----------|------|------|------|--------------|');
    for (const s of r.secrets) {
      lines.push(`| ${s.severity} | ${s.secretType} | ${path.basename(s.filePath)} | ${s.lineNumber} | \`${s.maskedValue}\` |`);
    }
  }

  lines.push(`\n---\n_Generated by Legacy Context Packager — 靜態分析結果，動態路由與反射產生的 API 不會出現於此。_`);

  return lines.join('\n');
}

function buildStatsSummary(r: ProjectScanResult): string {
  const lines: string[] = [];

  lines.push('| 項目 | 數量 |');
  lines.push('|---|---|');
  lines.push(`| API Routes | ${r.routes.length} |`);

  const controllers = new Set(
    r.routes.map(ro => ro.className ?? path.basename(ro.sourceFile)).filter(Boolean)
  );
  lines.push(`| Controllers / Handlers | ${controllers.size} |`);
  lines.push(`| Web Entries | ${r.webEntries.length} |`);

  const critCount = r.secrets.filter(s => s.severity === 'critical').length;
  lines.push(`| 疑似 Secrets | ${r.secrets.length}${critCount > 0 ? ` （critical: ${critCount}）` : ''} |`);

  if (controllers.size > 1) {
    lines.push('');
    lines.push('**Routes by Controller**');
    lines.push('');
    lines.push('| Controller | 路由數 |');
    lines.push('|---|---|');
    const countMap = new Map<string, number>();
    for (const ro of r.routes) {
      const key = ro.className ?? path.basename(ro.sourceFile);
      countMap.set(key, (countMap.get(key) ?? 0) + 1);
    }
    for (const [name, count] of [...countMap.entries()].sort((a, b) => b[1] - a[1])) {
      lines.push(`| ${name} | ${count} |`);
    }
  }

  return lines.join('\n');
}

function buildPkgDepsSection(deps: PkgDep[]): string {
  const lines: string[] = [];
  lines.push('| 套件 | 版本 | 來源 |');
  lines.push('|---|---|---|');
  for (const d of deps.slice(0, 40)) {
    lines.push(`| ${d.name} | ${d.version ?? '-'} | ${d.source} |`);
  }
  if (deps.length > 40) lines.push(`\n_（共 ${deps.length} 筆，僅顯示前 40）_`);
  return lines.join('\n');
}

function buildApiMapSection(routes: Route[], rootPath: string): string {
  if (routes.length === 0) return '_No routes found._';

  const lines: string[] = [];

  // 依 className 或 sourceFile basename 分組
  const groups = new Map<string, { sourceFile: string; routes: Route[] }>();
  for (const route of routes) {
    const key = route.className ?? path.basename(route.sourceFile, path.extname(route.sourceFile));
    if (!groups.has(key)) {
      groups.set(key, { sourceFile: route.sourceFile, routes: [] });
    }
    groups.get(key)!.routes.push(route);
  }

  const sorted = [...groups.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  lines.push(`> 共 ${routes.length} 個端點，分佈於 ${sorted.length} 個 Controller / Handler`);

  for (const [name, { sourceFile, routes: groupRoutes }] of sorted) {
    const relPath = path.relative(rootPath, sourceFile);
    lines.push('');
    lines.push(`### ${name}`);
    lines.push(`\`${relPath}\``);
    lines.push('');
    lines.push('| Method | Path | Handler | Confidence |');
    lines.push('|--------|------|---------|------------|');
    for (const route of [...groupRoutes].sort((a, b) => a.path.localeCompare(b.path))) {
      const handler = route.methodName ?? '-';
      lines.push(`| ${route.httpMethod} | \`${route.path}\` | ${handler} | ${route.confidence} |`);
    }
  }

  return lines.join('\n');
}
