import fs from 'fs';
import path from 'path';
import type { ProjectScanResult, ContextPackType } from '../models/context-pack.js';
import { generateContextPack } from './context-pack-generator.js';
import { buildReportHtml } from './report-builder.js';

export interface OutputOptions {
  outputDir: string;
  formats: ('json' | 'markdown')[];
  packs?: ContextPackType[];
  report?: boolean; // 是否產出 report.html（預設 true）
}

export function buildOutput(result: ProjectScanResult, opts: OutputOptions): void {
  fs.mkdirSync(opts.outputDir, { recursive: true });

  if (opts.formats.includes('json')) {
    writeJson(path.join(opts.outputDir, 'routes.json'), result.routes);
    writeJson(path.join(opts.outputDir, 'web-entry.json'), result.webEntries);
    writeJson(path.join(opts.outputDir, 'secrets-report.json'), result.secrets);
    writeJson(path.join(opts.outputDir, 'dependency-map.json'), result.dependencyMap);
    writeJson(path.join(opts.outputDir, 'openapi-lite.json'), result.openApiLite);
    writeJson(path.join(opts.outputDir, 'context-pack.json'), {
      projectInfo: result.projectInfo,
      summary: buildSummary(result),
    });
  }

  if (opts.formats.includes('markdown')) {
    const md = buildMarkdown(result);
    fs.writeFileSync(path.join(opts.outputDir, 'context-pack.md'), md, 'utf8');
  }

  // 產出互動式 HTML 報告（預設開啟）
  if (opts.report !== false) {
    const html = buildReportHtml(result);
    fs.writeFileSync(path.join(opts.outputDir, 'report.html'), html, 'utf8');
  }

  // 輸出各目的 context pack
  if (opts.packs && opts.packs.length > 0) {
    const packsDir = path.join(opts.outputDir, 'packs');
    fs.mkdirSync(packsDir, { recursive: true });
    for (const packType of opts.packs) {
      const content = generateContextPack(result, packType);
      fs.writeFileSync(path.join(packsDir, `${packType}.md`), content, 'utf8');
    }
  }
}

function writeJson(filePath: string, data: unknown): void {
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
}

function buildSummary(r: ProjectScanResult): Record<string, unknown> {
  return {
    totalRoutes: r.routes.length,
    totalWebEntries: r.webEntries.length,
    totalSecrets: r.secrets.length,
    criticalSecrets: r.secrets.filter(s => s.severity === 'critical').length,
    frameworks: [...new Set(r.routes.map(ro => ro.framework))],
  };
}

function buildMarkdown(r: ProjectScanResult): string {
  const lines: string[] = [];
  const { projectInfo: p } = r;

  lines.push(`# Context Pack — ${path.basename(p.rootPath)}`);
  lines.push(`\n> Language: \`${p.language}\` | Framework: \`${p.framework}\` | Scanned: ${p.scannedFiles}/${p.totalFiles} files | Duration: ${p.scanDurationMs}ms`);
  lines.push(`
## 給 LLM 的說明

你收到的是一份由靜態分析工具自動產生的遺留系統盤點摘要，資料來自原始碼的靜態掃描，未執行程式。請依下列順序完成系統盤點：

1. **技術棧摘要**：根據語言、框架與 config 檔案，描述此系統的技術選型與部署特徵
2. **功能模組拆解**：根據 Routes 的 Controller 分組，推斷各模組的職責與邊界
3. **前後端銜接**：對照 Web Entries 與 Routes，找出前端呼叫但後端可能缺少對應的路徑
4. **安全風險摘要**：若 Secrets 有資料，依嚴重程度列出需優先處理的項目；若無則標注「未偵測到硬編碼敏感值」
5. **盤點結論**：以條列式輸出「已釐清」與「需人工確認」的項目

**資料品質說明：**
- \`confidence: high\` 表示規則明確比對，可信度高
- \`confidence: medium / low\` 表示推斷結果，建議人工核實
- 動態路由、反射、自訂 middleware 產生的 API 不會出現在以下資料中`);

  lines.push('\n## Routes');
  if (r.routes.length === 0) {
    lines.push('_No routes found._');
  } else {
    lines.push('| Method | Path | Handler | Confidence |');
    lines.push('|--------|------|---------|------------|');
    for (const route of r.routes) {
      const handler = route.className
        ? `${route.className}${route.methodName ? '#' + route.methodName : ''}`
        : path.basename(route.sourceFile);
      lines.push(`| ${route.httpMethod} | \`${route.path}\` | ${handler} | ${route.confidence} |`);
    }
  }

  lines.push('\n## Web Entries');
  if (r.webEntries.length === 0) {
    lines.push('_No web entries found._');
  } else {
    lines.push('| Type | Source | Target | Invoke |');
    lines.push('|------|--------|--------|--------|');
    for (const e of r.webEntries) {
      lines.push(`| ${e.entryType} | ${path.basename(e.sourceFile)}:${e.lineNumber} | \`${e.targetPath}\` | ${e.invokeType} |`);
    }
  }

  lines.push('\n## Secrets');
  if (r.secrets.length === 0) {
    lines.push('_No secrets detected._');
  } else {
    lines.push('| Severity | Type | File | Line | Masked Value |');
    lines.push('|----------|------|------|------|--------------|');
    for (const s of r.secrets) {
      lines.push(`| ${s.severity} | ${s.secretType} | ${path.basename(s.filePath)} | ${s.lineNumber} | \`${s.maskedValue}\` |`);
    }
  }

  lines.push(`\n---\n_Generated by Legacy Context Packager — openapi-lite 為靜態近似結果，非完整 OpenAPI spec。_`);

  return lines.join('\n');
}
